version: '3'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATABASE: nest-pokemon
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db